<?php
/**
 * e-tailors.nl
 * http://e-tailors.nl
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@e-tailors.nl so we can send you a copy immediately.
 *
 * @category    Wigman
 * @package     Wigman_AjaxSwatches
 * @author      Willem Wigman - E-tailors <willem@e-tailors.nl)
 * @copyright   Copyright (c) 2014 (http://e-tailors.nl)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<!-- save the sites baseurl for Ajax references -->
<script lang="javascript">
    var posturl = "<?php echo Mage::getUrl('', array('_forced_secure' => $this->getRequest()->isSecure())); ?>";
<?php if($this->getActiveSwatchSelector()){ ?>
    var activeSwatchSelector = "<?php echo $this->getActiveSwatchSelector(); ?>";
<?php } ?>
</script>
